## Tipos de tensores

In [3]:
import torch

lista = [[1,2,3],[4,5,6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


## Outras forma de instanciar tensores

### Apartir de arrays Numpy

torch.from_numpy

In [4]:
import numpy as np
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print("Tipo de arra : ", arr.dtype)
print(tns)
print("Tipo de tensor : ", tns.dtype)

[[0.11291871 0.57709853 0.44858387 0.59411302]
 [0.3121328  0.36566497 0.19611744 0.53731955]
 [0.63242934 0.39706806 0.16411964 0.00210916]]
Tipo de arra :  float64
tensor([[0.1129, 0.5771, 0.4486, 0.5941],
        [0.3121, 0.3657, 0.1961, 0.5373],
        [0.6324, 0.3971, 0.1641, 0.0021]], dtype=torch.float64)
Tipo de tensor :  torch.float64


### Tensores inicializados

Essas funções recebem como parametro o tamanho de cada dimensão do tensor. 
Funções:

torch.ones() => Cria um tensor preenchido com zeros
torch.zeros() => Cria um tensor preenchido com uns.
torch.randn() => Cria um tensor preechifo com numeros aleatorias a apertir de uma distribuição normal

In [5]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsRand = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsRand)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.6162,  1.1785, -0.5558],
        [ 0.8321,  0.4282, -2.0282],
        [ 0.4358,  1.1672, -0.0685]])


### Converter Ternsor para Numpy

In [6]:
print(type(tnsRand))
arr = tnsRand.data.numpy()
print(type(arr))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### Indexação

De posse dessa informação, a indexação  é feita de forma similar a arrays Numpy, através da sintaxe de colchetes[]

In [7]:
print(tnsRand)
tnsRand[0, 2] = 5

print('')
print(tnsRand)

#Indexar com fatia da culona 2
print('')
print(tnsRand[:,2])

#Indexar um unico elemento
print('')
print(tnsRand[0,2])

tensor([[ 0.6162,  1.1785, -0.5558],
        [ 0.8321,  0.4282, -2.0282],
        [ 0.4358,  1.1672, -0.0685]])

tensor([[ 0.6162,  1.1785,  5.0000],
        [ 0.8321,  0.4282, -2.0282],
        [ 0.4358,  1.1672, -0.0685]])

tensor([ 5.0000, -2.0282, -0.0685])

tensor(5.)


### Operações com tensores

A função .item() utilizada anteriormente extrai o numero de um tensor que possui um valor, 
permitindo realizar as operações numericas do Python.
Caso o item não seja extraido, operações que envolvam tensores vão retornar novos tensores

Vale ressaltar também que operações entre tensores são realizadas ponto a ponto, operando cada elemento(i, j) do tensor t1,
com o elemento (i, j) do tensor t2


In [8]:
#Vericar o dimensão do tenser com a função shape
print(">Vericar o dimensão do tenser com a função shape")
print(tnsRand.shape)
print(tns1.shape)
print('')

#Ajustando as dimensões da matriz atrabes do fatiamento
print('>Ajustando as dimensões da matriz atrabes do fatiamento')
tns = tnsRand[0:2, :]
print(tns.shape)
print(tns1.shape)
print('')
print(tns)
print(tns1)
print('')
#Operaç~es de com tensores
print('>Soma de tensores')
print(tns + tns1)
print('')
print('>Multiplicação de tensores')
print(tns * tns1)
print('')
print('>Divisão de tensores')
print(tns / tns1)
print('')
print('>Multiplicação de tensores com a função mm()')
print(torch.mm(tns,tns1.T))

>Vericar o dimensão do tenser com a função shape
torch.Size([3, 3])
torch.Size([2, 3])

>Ajustando as dimensões da matriz atrabes do fatiamento
torch.Size([2, 3])
torch.Size([2, 3])

tensor([[ 0.6162,  1.1785,  5.0000],
        [ 0.8321,  0.4282, -2.0282]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])

>Soma de tensores
tensor([[ 1.6162,  2.1785,  6.0000],
        [ 1.8321,  1.4282, -1.0282]])

>Multiplicação de tensores
tensor([[ 0.6162,  1.1785,  5.0000],
        [ 0.8321,  0.4282, -2.0282]])

>Divisão de tensores
tensor([[ 0.6162,  1.1785,  5.0000],
        [ 0.8321,  0.4282, -2.0282]])

>Multiplicação de tensores com a função mm()
tensor([[ 6.7947,  6.7947],
        [-0.7680, -0.7680]])


### Funções .size() e .view()

Operações importantissima na manipulação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, linearizar um tensor n-dimensional

In [13]:
tns = torch.randn(2, 2, 3)
print(tns)
print('-----------------------------------------------------------------------------------------')
print(tns.size)
tns = tns.view(12)
print('-----------------------------------------------------------------------------------------')
print(tns)

tensor([[[ 6.8171e-02,  1.1598e+00,  1.2183e-03],
         [ 7.4336e-01,  1.3114e+00, -9.1900e-01]],

        [[ 5.9421e-01,  1.2942e+00, -2.8811e-01],
         [ 5.8574e-01, -1.6808e+00, -3.9587e-01]]])
-----------------------------------------------------------------------------------------
<built-in method size of Tensor object at 0x00000195D04DFE00>
-----------------------------------------------------------------------------------------
tensor([ 6.8171e-02,  1.1598e+00,  1.2183e-03,  7.4336e-01,  1.3114e+00,
        -9.1900e-01,  5.9421e-01,  1.2942e+00, -2.8811e-01,  5.8574e-01,
        -1.6808e+00, -3.9587e-01])


### GPU Cast

Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante definir o dispositivo no inicio do seu codigo de acordo com a verificaçao apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisarmos subir valores de GPU, como os pesos da rede, os gradientes 

In [16]:
import torch
tns = torch.randn(10)
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
    
print(device)

tns = tns.to(device)
print(tns)

cpu
tensor([-0.0643, -1.3389,  0.5803, -0.6348, -1.2710, -0.6448,  0.7023,  0.3582,
         1.2068,  1.3676])


### Para saber mais


In [22]:
tns1 = torch.randn(10)
tns2 = torch.randn(5)
tns_out = torch.cat( (tns1, tns2), dim=0 )

print(tns_out)

tensor([ 1.2853,  1.5829,  2.9143,  1.5234, -0.6752, -0.1168, -1.5200,  0.0987,
         1.9660, -1.5553, -0.1229,  0.1882,  1.7316, -0.4838, -1.2892])


https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops

In [23]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

#Função torch.mm retorno o produto de tns1 e tns2, ambos devem ter a mesma dimencionalidade
resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


### 05 Faça como eu fiz na aula

Nesta aula nos familiarizamos com o ambiente do Google Colab à medida que introduzimos a sintaxe básica do PyTorch para manipulação de tensores. Para trabalhar com redes neurais, a sua principal preocupação em relação aos tensores é garantir que sua dimensionalidade seja consistente com a operação que se deseja realizar.

Pensando nisso, crie um tensor aleatório tns1 com a dimensionalidade 7 x 7 x 3 e um outro tensor aleatório tns2 de 147 x 1. Modificando apenas tns1 some os dois tensores.

In [32]:
import torch

tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147,1)

print('TNS1 ',tns1)
print('TNS2 ',tns2)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2
print('==================================================================================================================')
print('SOMA DOS DOIS TENSORES ', soma)

TNS1  tensor([[[ 1.2969e+00,  6.8574e-01, -1.8200e+00],
         [-3.2747e-01, -1.5825e+00,  1.4378e+00],
         [ 8.1758e-01,  2.7950e-03, -1.7671e-01],
         [-8.4492e-01,  6.9002e-01,  1.5150e-01],
         [ 1.2314e+00, -1.5588e+00,  2.3067e+00],
         [ 1.6200e+00,  4.6692e-01, -1.1199e+00],
         [ 5.7047e-01,  3.8647e-01, -2.2152e+00]],

        [[-4.5597e-01, -1.5014e-01,  9.0590e-01],
         [-1.0812e-01, -9.2775e-01, -1.1947e+00],
         [ 1.2992e+00,  1.3495e-01,  5.1127e-01],
         [-2.8638e-01,  2.3488e-01, -2.9794e-01],
         [-6.0447e-02, -6.4214e-01, -8.1176e-01],
         [-1.2362e+00, -5.2753e-01,  5.6299e-01],
         [ 1.4219e+00,  9.8924e-02, -1.6388e+00]],

        [[-9.9021e-01, -1.5514e+00, -2.7535e-02],
         [-6.1939e-01, -3.9950e-02,  1.8954e-01],
         [-1.1293e+00,  6.5596e-01,  9.4099e-02],
         [-2.7216e-01, -9.6319e-01, -6.0650e-01],
         [ 7.7212e-01,  1.0598e+00,  3.5209e-01],
         [ 1.4961e+00, -2.4267e-01,  9.6

# 03 - Perceptron

### Classificação Linear

### Equação da Reta

A equação da reta é aprendida na forma ax + by + c, mas para nos adequarmos as nomenclaturas de rede neurais, podemos reescrever essas equação como w1*x1 + w2*x2 + b. Ou seja, w1, w2 e são os parametros  que definem o nosso medelo linear, a nosso reta.

Vamos começar realizando o plot de uma reta especifica: -1x1 + 4x2 + 0.4